python: '2.7'
numpy: '1.11'
package_versions:
  embree: 2.16.0
  boostcpp: "1.65.1"
  bullet: "2.86.1"
  cmake: "3.9.1"
  doxygen: "1.8.13"
  ds9: "7.5"
  eigen: "3.3.3"
  embree: "2.16.0"
  flann: "1.8.4"
  geos: "3.6.0"
  geotiff: "1.4.1"
  gsl: "2.2.1"
  hdf5: "1.8.18"
  lapack: "3.6.1"
  nanoflann: "1.2.2"
  ninja: "1.7.2"
  nn: "1.86.0"
  opencv: "3.3.0"
  patchelf: "0.9"
  pcl: "1.8.1"
  protobuf: "3.2.0"
  qhull: "7.2.0"
  qt: "5.7.1"
  qwt: "6.1.3"
  suitesparse: "4.5.4"
  superlu: "5.2.1"
  tbb: "4.4"
  libtiff: "4.0.6"
  vtk: "7.1.1"
  xalanc: "1.11"
  xercesc: "3.1.4"
run_dependencies:
  boost: "1.65*"
  blas: ""
  boost: "1.65*"
  bzip2: ">=1.0.6,<2.0a0"
  curl: ""
  eigen: ""
  expat: ""
  ffmpeg: ">=3.2.3,<3.2.6"
  flann: ""
  harfbuzz: "1.3.4"
  hdf5: "1.8.18|1.8.18.*"
  icu: "58.*"
  jasper: ""
  jpeg: "9*"
  libcxx: ">=4.0.1"
  libgcc: ""
  libgfortran: ""
  libiconv: ""
  libpng: ">=1.6.28,<1.7"
  libprotobuf: "3.2.0"
  libtiff: "4.0.*"
  libuv: ""
  libwebp: "0.5.*"
  m4: ""
  metis: "5.1.*"
  ncurses: "6.*"
  numpy: ">1.8"
  openblas: "0.2.19|0.2.19.*"
  python: "<3"
  qt: "5.7.1"
  rhash: ""
  six: ""
  tbb: ""
  xercesc: ""
  xz: ">=5.2.3,<6.0a0"
  zlib: ">=1.2.11,<1.3.0a0"
